apiVersion: v1
kind: ReplicationController
metadata:
    name:  myrc1
spec:
   selector:
      app: web
   template:
      metadata:
         name: "mypod1"
         labels:
           app: web
      spec:
         containers:
         -  name: "myc1"
             image: "vimal13/apache-webserver-php"